Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  
  NatGatewaytoInternet:
    Description: if BeckEnd has access to internet 
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'
  ifBackendexist:
    Description: if Backend 
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'

Conditions:
 NatGateway: !Equals
   - !Ref NatGatewaytoInternet 
   - 'Yes'
 
 ifBackend : !Equals
   - !Ref ifBackendexist 
   - 'Yes'

 NatandBackend: !And
   - !Condition NatGateway
   - !Condition ifBackend


Mappings: 
  RegionMap: 
  # Paris
    eu-west-3:
      bastion: ami-01c72e187b357583b
      backend: ami-01c72e187b357583b
  # Ireland      
    eu-west-1:
      bastion: ami-0b4b2d87bdd32212a
      backend: ami-0b4b2d87bdd32212a
  # Frankfurt  
    eu-central-1:
      bastion: ami-0e342d72b12109f91
      backend: ami-0e342d72b12109f91
  # London      
    eu-west-2:
      bastion: ami-0eb89db7593b5d434
      backend: ami-0eb89db7593b5d434  # ubuntu
    


Resources:
# internet bucket 
  S3Buckethtml:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: "jenkinscredentionalinit"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html



# user definition 
  User:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 's3:*object'
                Resource: 
                   - 'arn:aws:s3:::jenkinssetup/*'
                   - 'arn:aws:s3:::jenkinscredentionalinit/*'
                   - 'arn:aws:s3:::jenkinscredentionalinit'
                   - 'arn:aws:s3:::testuploadfileyaml/*'
                    
        - PolicyName: IAMAccess
          PolicyDocument:
            Statement:
              - Effect: Allow
                NotAction: 'iam:*'
                Resource: '*'
        - PolicyName: EC2Access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 'ec2:*'
                Resource: '*'

  HostKeys:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref User
# Roles definition
  assumebucketRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "bucketaccess"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
           # Principal: 
            Action:
                - 's3:*Object'
                - 's3:List*'
                
            Resource: 
               - 'arn:aws:s3:::jenkinssetup/configurefile/*'
               - 'arn:aws:s3:::jenkinssetup/*'
               - 'arn:aws:s3:::jenkinscredentionalinit/*'
      Roles: 
        - 
          Ref: "assumebucketRole"
  
  assingInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          Ref: "assumebucketRole"

# network definition 
  pierwszaSiecVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudmarszolekstack.s3-eu-west-1.amazonaws.com/jenkins_network.yaml
      Parameters: 
        NatGatewaytoInternet: !Ref NatGatewaytoInternet
        ifBackendexist: !Ref ifBackendexist
      TimeoutInMinutes: 5
  
  # security group 
  publicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDP to Bastion
      VpcId: !GetAtt pierwszaSiecVPC.Outputs.VPCId
      SecurityGroupIngress:
          -
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          -
            IpProtocol: tcp
            FromPort: 8080
            ToPort: 8080
            CidrIp: 0.0.0.0/0
            
      SecurityGroupEgress:
          -
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - 
            IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: 0.0.0.0/0
          -
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 10.10.1.0/24
          -
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 10.10.2.0/24
            
            
            
  privateSecurityGroupNat:
    Condition: NatandBackend
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from Bastion
      VpcId: !GetAtt pierwszaSiecVPC.Outputs.VPCId
      SecurityGroupIngress:
          -
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            SourceSecurityGroupId: !Ref publicSecurityGroup 

      
      SecurityGroupEgress:
          -
            IpProtocol: tcp
            FromPort: 0
            ToPort: 65535
            DestinationSecurityGroupId: !Ref publicSecurityGroup
          - 
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - 
            IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: 0.0.0.0/0
            
  privateSecurityGroupNatwithout:
    Condition: ifBackend
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from Bastion
      VpcId: !GetAtt pierwszaSiecVPC.Outputs.VPCId
      SecurityGroupIngress:
          -
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            SourceSecurityGroupId: !Ref publicSecurityGroup 

      
      SecurityGroupEgress:
          -
            IpProtocol: tcp
            FromPort: 0
            ToPort: 65535
            DestinationSecurityGroupId: !Ref publicSecurityGroup
         
  # Bastion
  
  Ec2InstanceBastion: 
    Type: AWS::EC2::Instance
    Properties: 
     ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", bastion]
     InstanceType: 't2.micro'
     KeyName: !Ref KeyName 
     IamInstanceProfile: !Ref assingInstanceProfile
     SubnetId: 
          !GetAtt pierwszaSiecVPC.Outputs.PublicSubentid
     SecurityGroupIds:
        -
          !Ref publicSecurityGroup
     Tags:
        - Key: "projekt"
          Value: "pierwszaSiec"
        

     UserData:
      'Fn::Base64':
         !Sub |
         #!/bin/bash
         sudo yum update -y
         sudo yum install -y java-1.8.0-openjdk.x86_64 
         sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo 
         sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key 
         sudo yum install jenkins -y 
         sudo service jenkins start 
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         sudo ./aws/install
         sudo aws configure set aws_access_key_id ${HostKeys}
         sudo aws configure set aws_secret_access_key ${HostKeys.SecretAccessKey}
         sudo aws configure set default.region ${AWS::Region}
         aws s3 cp /tmp/log.txt s3://jenkinssetup/configurefile/log.txt
         aws s3 cp s3://jenkinssetup/configurefile/PierwszaSiec.pem /home/ec2-user/PierwszaSiec.pem
         aws s3 cp s3://jenkinssetup/configurefile/PierwszaSiec.ppk /home/ec2-user/PierwszaSiec.ppk
         sleep 360
         sudo cp /var/lib/jenkins/secrets/initialAdminPassword  /tmp/cred.txt 
         cred=$(cat /tmp/cred.txt)
         echo "<html><head><title></title></head><body><p>This is credetional $cred</p></body></html>" >> /tmp/index.html
         aws s3 cp /tmp/index.html s3://jenkinscredentionalinit/index.html  --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
                  
         
           
           
  
  
  # Backends 

  Ec2InstanceBackEnd1: 
    Condition: ifBackend
    Type: AWS::EC2::Instance
    Properties: 
     ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", backend]
     InstanceType: 't2.micro'
     KeyName: !Ref KeyName 
 
     SubnetId: 
          !GetAtt pierwszaSiecVPC.Outputs.Private1Subentid
     SecurityGroupIds:
        -
          !If [ NatGateway, !Ref privateSecurityGroupNat, !Ref privateSecurityGroupNatwithout]
     Tags:
        - Key: "projekt"
          Value: "pierwszaSiec"


  Ec2InstanceBackEnd2: 
    Condition: ifBackend
    Type: AWS::EC2::Instance
    Properties: 
     ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", backend]
     InstanceType: 't2.micro'
     KeyName: !Ref KeyName 
   
     SubnetId: 
          !GetAtt pierwszaSiecVPC.Outputs.Private2Subentid
     SecurityGroupIds:
        -
          !If [ NatGateway, !Ref privateSecurityGroupNat, !Ref privateSecurityGroupNatwithout]
     Tags:
        - Key: "projekt"
          Value: "pierwszaSiec"



  
# out put


Outputs:
    IPAdressBastoin:
      Description: "Bastion IP Addres"
      Value: !GetAtt   Ec2InstanceBastion.PublicIp
      Export:
        Name: "BastionIPaddress"
    IPAdressBackEnd1:
      Condition: ifBackend
      Description: "BackEnd1 IP Addres"
      Value: !GetAtt   Ec2InstanceBackEnd1.PrivateIp
      Export:
        Name: "Backend1IPaddress"        
    IPAdressBackEnd2:
      Condition: ifBackend
      Description: "BackEnd2 IP Addres"
      Value: !GetAtt   Ec2InstanceBackEnd2.PrivateIp
      Export:
        Name: "Backend2IPaddress"           
    WebsiteURL:
      Value: !GetAtt [S3Buckethtml, WebsiteURL]
      Description: URL for website hosted on S3
    JenkinsWeb:
      Value: !Join ['', ['http://',!GetAtt   Ec2InstanceBastion.PublicIp,':8080']]
    


   